spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/weixin?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
#  jackson:
#    default-property-inclusion: non_null   为空的值不打印出来



server:
  context-path: /sell

wechat:
      mpAppId: wxd898fcb01713c658
      mpAppSecret: 29d8a650db31472aa8700e3b0d739f2
      mchId:
      mchKey:
      keyPath:
#微信支付异步通知地址
      notifyUrl: http://sell.natapp4.cc/sell/pay.notify


logging:
  pattern:
    console: "%d-%msg%n"
  file: G:\xuwanying2\sell\sell.log
